# Variable :- 

 - Variables allow us to add new trainable parameters to the graph.
 
__Syntax : tf.variable()__

Note : Suppose we want to create tensor and if we want to change in future, then that time we have to use above syntax for variable creation. 

### How to create Variable in TensorFlow

The Variable() consturctor requires an initial value for the variable, which can be a Tensor of any type and shape. This initial value defines the type and shape of the variable. __After construction, the type and shape of the variable are fixed. The value can be changed using one the assign methods__. 

## Syntax :
tf.Variable(
        initial_value=None, trainable=None, validate_shape=True, caching_device=None,
        name=None, variable_def=None, dtype=None, import_scope=None, constraint=None,
        synchronization=tf.VariableSynchronization.AUTO,
        aggregation=tf.compat.v1.VariableAggregation.NONE, shape=None
    )

__Reference link__ : https://www.tensorflow.org/api_docs/python/tf/Variable

In [1]:
#Import tensorflow

import tensorflow as tf

In [2]:
# Create Tensor

tf.Variable(1)

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=1>

In [3]:
a = tf.Variable([1,2,3,4]) #assing variable
a

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4])>

In [4]:
 a.name

'Variable:0'

In [5]:
a.shape

TensorShape([4])

In [6]:
a.dtype

tf.int32

In [7]:
a.numpy()

array([1, 2, 3, 4])

In [8]:
type(a)

tensorflow.python.ops.resource_variable_ops.ResourceVariable

# Create TensorFlow using Various data types

In [9]:
#Create tensorflow using interger
tf_int =tf.Variable([1,2,3,4,5,6])
tf_int

<tf.Variable 'Variable:0' shape=(6,) dtype=int32, numpy=array([1, 2, 3, 4, 5, 6])>

In [10]:
#Create tensorflow using Float 
tf_flt =tf.Variable([1,2,3.5,4.2,5,6])
tf_flt

<tf.Variable 'Variable:0' shape=(6,) dtype=float32, numpy=array([1. , 2. , 3.5, 4.2, 5. , 6. ], dtype=float32)>

In [11]:
#Create tensorflow using string
tf_str = tf.Variable(['a','b','c','d'])
tf_str

<tf.Variable 'Variable:0' shape=(4,) dtype=string, numpy=array([b'a', b'b', b'c', b'd'], dtype=object)>

In [12]:
#Create tensorflow using boolean
tf_bool = tf.Variable([True, False])
tf_bool

<tf.Variable 'Variable:0' shape=(2,) dtype=bool, numpy=array([ True, False])>

In [13]:
#Create tensorflow using Complex Number
tf_complex = tf.Variable('2+3j')
tf_complex

<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'2+3j'>

## Create tensorFlow from Constant Tensorflow Variable

In [14]:
tf_cnst = tf.constant([1,2,3,4])
tf_cnst

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4])>

In [15]:
tf.Variable(tf_cnst)

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4])>

## Create TensorFlow variable with different Shape

In [16]:
tf_2d = tf.Variable([[1,2],[3,4]])
tf_2d

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

## Or

In [17]:
tf_2d_a = tf.Variable([1,2,3,4])

In [18]:
tf_2d_a

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4])>

In [19]:
tf.reshape(tf_2d_a,(2,2))

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

## Get Index of Highest Value

In [20]:
tf_2d = tf.Variable([[1,2],[3,4]])
tf_2d

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

In [21]:
tf.argmax(tf_2d) #find the maximum value of index

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([1, 1], dtype=int64)>

In [26]:
tf.argmax(tf_2d).numpy() #maximum value of index

array([1, 1], dtype=int64)

## Viewed/convert as a Tensor

In [31]:
a = tf.Variable([1,2,3,4])
a

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4])>

In [32]:
tf.convert_to_tensor(a)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4])>

In [33]:
tf_2d

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

In [34]:
tf.convert_to_tensor(tf_2d)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

## Change/Assign new Value to Tensor

In [35]:
a

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4])>

In [36]:
a.assign([2,4,6,8])

<tf.Variable 'UnreadVariable' shape=(4,) dtype=int32, numpy=array([2, 4, 6, 8])>

## Assign Variable with another memory 

In [37]:
a.assign_add([2,4,6,8])

<tf.Variable 'UnreadVariable' shape=(4,) dtype=int32, numpy=array([ 4,  8, 12, 16])>

## We can't change shape and Data Type

In [40]:
a.assign([4.5,5,6.5,7,8])

TypeError: Cannot convert [4.5, 5, 6.5, 7, 8] to EagerTensor of dtype int32