 ### 1] Constant :- 
- Create a constant tensor from a tensor-like object.
     
__Syntax : tf.constant()__

__Note__ : Once we create tensor we can not change later. 

## How to create Constant variable in TensorFlow. 

__tf.constant():__
    
Create a constant tensor from a tensor-like object. 

Args
Values    A constant value(or list) of output type dtype.
dtype     The type of the elements of the resulting tensor.
shape     Optional dimensions of reslting tensor. 
name      Optional name for the tensor.


Returns
A Constant Tensor.

refernece link :https://www.tensorflow.org/api_docs/python/tf/constant

 ## Notes
 
 1. tf.session() not in 2.x
 2. Most of TensorFlow syntax same like NumPy
 3. Use : While building neural network graph need constant variable like input data, it neer change while traning. 

In [1]:
# Import tensorflow

import tensorflow as tf

In [2]:
# checking Tensroflow version 

tf.__version__

'2.6.0'

In [3]:
# checking GPU Availability

tf.test.is_gpu_available()

Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.


True

In [4]:
# Create Integer Constant

tft1 = tf.constant(15)

In [5]:
tft1

<tf.Tensor: shape=(), dtype=int32, numpy=15>

In [6]:
# Create Flot Constant 

tft2 = tf.constant(120.1)

In [7]:
tft2

<tf.Tensor: shape=(), dtype=float32, numpy=120.1>

In [8]:
# Create Sting constant

tft3 = tf.constant('My name is Sunil and i love to code !')

In [9]:
tft3

<tf.Tensor: shape=(), dtype=string, numpy=b'My name is Sunil and i love to code !'>

Here, b is denote byte string

In [10]:
# Create boolean Constant

tft4 = tf.constant(True)

In [11]:
tft4

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [12]:
# Create constant NumPy array/List/Tuple
import numpy as np

In [13]:
np.array = tf.constant(np.array([1,2,3,4]))

In [14]:
np.array

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4])>

In [15]:
# Create 1D Constant
t1d = tf.constant([1,2,3,4])

In [16]:
t1d

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4])>

In [17]:
# Create 1D Constant
t2d = tf.constant([[1,3],[1,0]])

In [18]:
t2d

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 3],
       [1, 0]])>

## Or

In [19]:
# Define Shape
t2d_a = tf.constant([1,2,3,4], shape = (2,2))

In [20]:
t2d_a

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

In [21]:
#Define data type
t2d_b = tf.constant([1,2,3,4], shape = (2,2), dtype ='float32')

In [22]:
t2d_b

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

#### Create N- dimension Constant



In [23]:
t3d = tf.constant([[1,3],[1,0],[0,8]])

In [24]:
t3d

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 3],
       [1, 0],
       [0, 8]])>

## Or

In [28]:
t3d_a = tf.constant([[1,3,1,0,0,8]], shape= (2,3))

In [29]:
t3d_a

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 3, 1],
       [0, 0, 8]])>

In [30]:
t3d_b = tf.constant([[1,3,1,0,0,8]], shape= (2,3), dtype = 'float')

In [31]:
t3d_b

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 3., 1.],
       [0., 0., 8.]], dtype=float32)>

#### Type of constant

In [32]:
type(t3d_b)

tensorflow.python.framework.ops.EagerTensor

#### Shape of constant

In [33]:
t3d_b.shape

TensorShape([2, 3])

#### Access Constant Value

In [34]:
t3d_b.numpy()

array([[1., 3., 1.],
       [0., 0., 8.]], dtype=float32)

#### Constant Dtype

In [38]:
t3d_b.dtype

tf.float32